export const LABELS_FETCHED = 'LABELS_FETCHED'
export const LABEL_CREATED = 'LABEL_CREATED'
export const LABEL_UPDATED = 'LABEL_UPDATED'
export const LABEL_REMOVED = 'LABEL_REMOVED'

export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'
export const CATEGORY_CREATED = 'CATEGORY_CREATED'
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED'
export const CATEGORY_REMOVED = 'CATEGORY_REMOVED'

export const UNITS_FETCHED = 'UNITS_FETCHED'
export const UNIT_CREATED = 'UNIT_CREATED'
export const UNIT_UPDATED = 'UNIT_UPDATED'
export const UNIT_REMOVED = 'UNIT_REMOVED'
